# ============================================================================ #
#                          C h e c k o v   c o n f i g
# ============================================================================ #

# https://github.com/bridgecrewio/checkov#configuration-using-a-config-file
#
# This is not well documented but the fields seem to be the same as:
#
#   checkov --help
#
# See master template at:
#
#   https://github.com/harisekhon/Templates/blob/master/.checkov.yaml

---
compact: true
directory:
  - .
download-external-modules: true  # without this gets lots of annoying warning lines such as '2022-02-22 16:14:40,180 [MainThread  ] [WARNI]  Failed to download module x/y/z:n.n.n'
framework:
  - all
no-guide: true
output: cli
quiet: true
repo-id: buluma/GitHub-Actions  # what to report to Bridgecrew Cloud - without this gets annoying duplicate repos such as 'buluma_cli_repo/github-actions'
skip-suppressions: true
soft-fail: true
