---
name: Close Stale Issues and PRs
on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  issues: write
  pull-requests: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          exempt-issue-labels: pinned
          stale-pr-label: stale
          stale-issue-label: stale
