---
name: Codeowners

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  GH_TOKEN: ${{ github.token }}
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  validate:
    name: Validate CODEOWNERS
    runs-on: ubuntu-latest
    container: harisekhon/bash-tools:latest
    steps:
      - name: Environment
        run: env | sort

      - name: GH CLI auth status
        run: |
          gh config set prompt disabled
          gh auth status

      - name: Check Codeowners Errors
        run: |
          check_github_codeowners.sh "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME"
