---
name: macOS

on:
  workflow_call:
    inputs:
      version:
        description: The macOS version eg. latest, 10.15, 11
        type: string
        required: true
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  build:
    name: Build
    runs-on: macos-${{ inputs.version }}
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v4
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      #- uses: actions/cache@v1
      #  with:
      #    path: ~/Library/Caches/pip
      #    key: ${{ runner.os }}-pip-bash-tools  # -${{ hashFiles('**/requirements.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pip-bash-tools
      #
      #- uses: actions/cache@v1
      #  with:
      #    path: ~/.cpanm
      #    key: ${{ runner.os }}-cpanm-bash-tools-${{ hashFiles('**/cpan-requirements.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-cpanm-bash-tools

      - name: Brew Update
        run: which brew && brew update || echo

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
