---
name: Make

on:
  workflow_call:
    inputs:
      container:
        description: The docker image:version container to build inside
        type: string
        required: true
      build-target:
        description: The Make build target
        type: string
        required: false
        default: ''
      no-test:
        description: Don't run 'make test' after build
        type: boolean
        required: false
        default: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: sh -eux {0}

env:
  BUILD_TARGET: ${{ inputs.build-target || github.event.inputs.build-target }}
  DEBIAN_FRONTEND: noninteractive
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Environment
        run: env | sort

      - name: Install Git & Make
        run: |
          if command -v apk; then
            # apk add --no-cache isn't available until Alpine 3
            #apk add --no-cache git make
            apk update && apk add git make
          elif command -v apt-get; then
            if grep -Fxq 'ID=debian' /etc/*release &&
               grep -xq 'VERSION_ID="[67]"' /etc/*release; then
              # switch APT sources to archive.debian.org
              sed -i 's/deb.debian.org/archive.debian.org/' /etc/apt/sources.list
              sed -i 's/security.debian.org/archive.debian.org/' /etc/apt/sources.list
            fi
            apt-get update
            apt-get install -y -q git make
          #elif command -v dnf; then
          #  dnf install -y -q git make
          elif command -v yum; then
            # CentOS is EOL - but for some reason CentOS 7 works without this, while CentOS 6 and 8 need archive
            if grep -qi centos /etc/*release && grep -q '^VERSION="[68]"$' /etc/*release; then
              sed -i 's/^[[:space:]]*mirrorlist/#mirrorlist/' /etc/yum.repos.d/CentOS-*
              sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|' /etc/yum.repos.d/CentOS-*
            fi
            yum install -y -q git make
          fi

      - name: Git version
        run: git --version

      - name: Git Checkout
        # git version too old to support recursive submodules checkout on older version Debian and Ubuntu <= 18
        #uses: actions/checkout@v4
        #with:
        #  submodules: recursive  # requires Git 2.18+ to be installed first
        run: git clone "https://${{github.token}}@github.com/$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE"

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if [ -n "${BUILD_TARGET:-}" ] &&
             grep -q "^$BUILD_TARGET:" Makefile; then
             make "$BUILD_TARGET"
          elif grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        if: inputs.no-test != true && github.event.inputs.no-test != true
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
