---
name: Merge Branch

on:
  workflow_call:
    inputs:
      head:
        description: Branch to merge from (defaults to triggered branch if not specified)
        type: string
        required: false
      base:
        description: Branch to merge into
        type: string
        required: true
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      head:
        description: Branch to merge from (defaults to triggered branch if not specified)
        type: string
        required: false
      base:
        description: Branch to merge into
        type: string
        required: true
      debug:
        type: boolean
        required: false
        default: false

# without 'contents: write' permission the PR merge fails with the error:
# Message: Resource not accessible by integration, Locations: [{Line:1 Column:58}]
permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  GH_TOKEN: ${{ github.token }}
  GH_NO_UPDATE_NOTIFIER: 1
  HEAD: ${{ inputs.head || github.event.inputs.head }}
  BASE: ${{ inputs.base || github.event.inputs.base }}
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false  # killing this part way through may leave PRs without auto-merging

jobs:
  merge_branch:
    name: Merge Branch
    runs-on: ubuntu-latest
    container: harisekhon/bash-tools
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v2

      - name: GH CLI auth status
        run: |
          gh config set prompt disabled
          gh auth status

      - name: check/generate HEAD environment variable
        run: |
          if [ -z "$HEAD" ]; then
            if [ "$GITHUB_REF_TYPE" != "branch" ]; then
              echo "HEAD branch not specified and cannot infer from trigger branch as triggered from '$GITHUB_REF_TYPE' instead of branch"
              exit 1
            fi
            echo "HEAD branch not specified, assuming trigger branch '$GITHUB_REF_NAME'"
            echo "HEAD=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          fi

      - name: Merge Branch ${{ env.HEAD }} into ${{ env.BASE }}
        run: |
          github_merge_branch.sh "$HEAD" "$BASE"
