---
name: Pluto

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  pluto:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master

      - name: Pluto detect-files
        run: |
          pluto detect-files -d .
