---
name: Polaris

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v4

      - name: Polaris Audit
        uses: fairwindsops/polaris@master
        with:
          #version: 4.0.7
          #
          # audit may fail on repos with JSON patches such as https://github.com/harisekhon/Kubernetes-configs:
          #
          #   https://github.com/FairwindsOps/polaris/issues/667
          #
          #   and can't exclude files:
          #
          #     https://github.com/FairwindsOps/polaris/issues/670
          #
          # the better solution is to run Polaris inside Kubernetes, see polaris*.yaml in:
          #
          #   https://github.com/harisekhon/Kubernetes-configs
          #
          args: polaris audit --audit-path . -f pretty --only-show-failed-tests
