#
#  Author: Hari Sekhon
#  Date: 2020-02-04 21:40:04 +0000 (Tue, 04 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Python

on:
  workflow_call:
    inputs:
      version:
        description: Python version for actions/setup-python
        type: string
        required: true
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.version }}

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-bash-tools

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
