#
#  Author: Hari Sekhon
#  Date: 2022-01-21 18:25:55 +0000 (Fri, 21 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

# ============================================================================ #
#                  S e m g r e p   C l o u d   W o r k f l o w
# ============================================================================ #

# Logs results to https://semgrep.dev/

---
name: Semgrep Cloud

on:
  pull_request: {}
  push:
    branches:
      - master
      - main
    paths: []
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
    secrets:
      SEMGREP_APP_TOKEN:
        required: true
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  semgrep:
    name: Semgrep Scan, Cloud report
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - uses: returntocorp/semgrep-action@v1
        with:
          auditOn: push
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          # Change job timeout (default is 1800 seconds; set to 0 to disable)
          # env:
          #   SEMGREP_TIMEOUT: 300
