#
#  Author: Hari Sekhon
#  Date: Wed Jan 19 19:11:31 2022 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

# ============================================================================ #
#                        S e m g r e p   W o r k f l o w
# ============================================================================ #

# Generates code scanning alerts in GitHub's Security tab -> Code scanning alerts

# https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions

---
name: Semgrep

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  semgrep:
    name: Semgrep Scan, GitHub security report
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Environment
        run: env | sort

      # ubuntu-latest already has this installed and a newer version
      #- name: Install Git
      #  run: sudo apt-get update && sudo apt-get install -y git --no-install-recommends

      - name: Git version
        run: git --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets

        # == Optional settings in the `with:` block

        # Instead of `config:`, use rules set in Semgrep App.
        # Get your token from semgrep.dev/manage/settings.
        #   publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}

        # Never fail the build due to findings on pushes.
        # Instead, just collect findings for semgrep.dev/manage/findings
          #auditOn: push
          auditOn: push workflow_dispatch cron
          generateSarif: "1"

        # Change job timeout (default is 1800 seconds; set to 0 to disable)
        #env:
          #SEMGREP_AGENT_DEBUG: 1
          #SEMGREP_TIMEOUT: 300

      # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
