---
name: Terraform Validate

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

defaults:
  run:
    # hashicorp/terraform doesn't have bash
    #shell: bash -euxo pipefail {0}
    shell: sh -eux {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    container: hashicorp/terraform:latest
    steps:
      - name: Environment
        run: env | sort

      # hashicorp/terraform does have git
      - name: Git version
        run: git --version

      - uses: actions/checkout@v4
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
