# ============================================================================ #
#                   T F s e c   G i t H u b   W o r k f l o w
# ============================================================================ #

# Comments on any PR that adds transgressions

# https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/github-actions/pr-commenter/

---
name: tfsec-pr-commenter

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v4

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@5e9f770638057da497182661aacbf640ca94f4e9
        with:
          github_token: ${{ github.token }}
          # or
          #github_token: ${{ secrets.GITHUB_TOKEN }}
