# ============================================================================ #
#                   T F s e c   G i t H u b   W o r k f l o w
# ============================================================================ #

# Static analysis of Terraform code - publishes report to GitHub Security tab

# https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/github-actions/github-action/

---
name: tfsec

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  actions: read
  contents: read
  security-events: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  tfsec:
    name: tfsec scan & sarif report
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v2

      - name: tfsec
        #uses: tfsec/tfsec-sarif-action@main
        uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif
          #config_file: tfsec.yaml  # default: .tfsec/config.yaml
          #working_directory: terraform/
          #github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
