---
name: Trivy Docker Image Scan

on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/trivy.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - .github/workflows/trivy.yaml
  workflow_call:
    inputs:
      docker_image:
        description: The docker image:tag for Trivy to analyze
        type: string
        required: true
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      docker_image:
        description: The docker image:tag for Trivy to analyze
        type: string
        required: true
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  # ${{ inputs.* }}               is set by workflow_call
  # ${{ github.events.inputs.* }} is set by workflow_dispatch
  DOCKER_IMAGE: ${{ inputs.docker_image || github.event.inputs.docker_image || 'buluma/bash-tools' }}
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  trivy:
    name: Trivy Docker Image Scan
    runs-on: ubuntu-latest
    container: aquasec/trivy:latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v4

      - name: Trivy (Full Informational)
        run: |
          # informational to see all issues
          trivy image --no-progress "$DOCKER_IMAGE"

      - name: Trivy (with Severity Error Out)
        if: ${{ inputs.severity || github.event.inputs.severity }}
        env:
          SEVERITY: ${{ inputs.severity || github.event.inputs.severity }}
        run: |
          # fail the pipeline if any of the issues are in $SEVERITY eg. HIGH,CRITICAL
          trivy image --no-progress --exit-code 1 --severity "$SEVERITY" "$DOCKER_IMAGE"
