---
name: Trivy Filesystem Scan

on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/trivy_fs.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - .github/workflows/trivy_fs.yaml
  workflow_call:
    inputs:
      path:
        description: The filesystem path for Trivy to analyze
        type: string
        default: .
        required: false
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      path:
        description: The filesystem path for Trivy to analyze
        type: string
        default: .
        required: false
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  # ${{ inputs.* }}               is set by workflow_call
  # ${{ github.events.inputs.* }} is set by workflow_dispatch
  SCAN_PATH: ${{ inputs.path || github.event.inputs.path || '.' }}
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  trivy:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    container: aquasec/trivy:latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v2

      - name: Trivy (Full Informational)
        run: |
          # informational to see all issues
          trivy fs --no-progress "$SCAN_PATH"

      - name: Trivy (with Severity Error Out)
        if: ${{ inputs.severity || github.event.inputs.severity }}
        env:
          SEVERITY: ${{ inputs.severity || github.event.inputs.severity }}
        run: |
          # fail the pipeline if any of the issues are in $SEVERITY eg. HIGH,CRITICAL
          trivy fs --no-progress --exit-code 1 --severity "$SEVERITY" "$SCAN_PATH"
