---
name: Trivy GitHub Security Alerts

on:
  workflow_call:
    inputs:
      target:
        description: The Trivy target to analyze, usually a docker image:tag
        type: string
        required: true
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      target:
        description: The Trivy target to analyze, usually a docker image:tag
        type: string
        required: true
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  actions: read
  contents: read
  security-events: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  # ${{ inputs.* }}               is set by workflow_call
  # ${{ github.events.inputs.* }} is set by workflow_dispatch
  TARGET: ${{ inputs.target || github.event.inputs.target }}
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  trivy:
    name: Trivy GitHub Security Alerts
    runs-on: ubuntu-latest
    container: aquasec/trivy:latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner to generate sarif
        if: ${{ ! ( inputs.no_sarif || github.event.inputs.sarif ) }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.TARGET }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif

      - name: Upload Trivy sarif scan results to GitHub Security tab
        if: ${{ ! ( inputs.no_sarif || github.event.inputs.sarif ) }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
