---
name: GitHub Actions Ubuntu

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBIAN_FRONTEND: noninteractive
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - name: Install Git & Make
        run: sudo apt-get update && sudo apt-get install -y git make

      - name: Git version
        run: git --version

      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
