---
name: URL Links

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      url_links_ignored:
        type: string
        required: false
      ignore_urls_without_dots:
        type: string
        required: false
    #  env:
    #    type: string  # pass in string in export shell format eg. export MYVAR=myvalue MYVAR2=myvalue2
    #    required: false
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  check_url_links:
    name: Check URL Links
    runs-on: ubuntu-latest
    container: harisekhon/bash-tools
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      #- uses: actions/checkout@v2
      #  with:
      #    repository: HariSekhon/DevOps-Bash-tools
      #    #ref: master            # unset for default branch in case it changes in future
      #    #submodules: recursive  # don't need the submodules for just this script, save time
      #    path: bash-tools

      - name: Check URL Links
        env:
          #DEBUG: 1
          VERBOSE: 1
          URL_LINKS_IGNORED: ${{ inputs.url_links_ignored }}
          IGNORE_URLS_WITHOUT_DOTS: ${{ inputs.ignore_urls_without_dots }}
        run: |
          # extended PATH gives option of using bash tools checkout or version from container
          export PATH="$PWD/bash-tools:$PATH"

          # this is just to account for the examples in the .github/workflows/README.md in this own repo
          if [ -z "$URL_LINKS_IGNORED" ]; then
            export URL_LINKS_IGNORED="
              http://krb5server
              https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv
              https://megalinter.github.io
            "
          fi

          check_url_links.sh
