---
name: Validation

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      # doesn't evaluate in time for container
      #docker_image_tag:
      #  type: string
      #  required: true
      #  default: latest
      # workflow calls only permit string/boolean/number - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
      env:
        type: string  # pass in string in export shell format eg. export MYVAR=myvalue MYVAR2=myvalue2
        default: ''
        required: false
      debug:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  INPUTS: ${{ inputs.env }}
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    # PyTools contains some extra tools, eg. use validate_yaml.py if check_yaml.sh yamllint dependencies aren't available
    # inputs evaluates to blank and fails to pull - not available at this stage
    #container: buluma/pytools:${{ inputs.docker_image_tag }}
    #container: buluma/pytools:debian
    container: buluma/pytools:centos
    #container: buluma/bash-tools:latest
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v4
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - name: Setup environment variables
        run: |
          echo "${{ env.INPUTS }}" >> "$GITHUB_ENV"

      - name: Environment
        run: env | sort

      - name: Validate
        run: |
          if [ -f .validate.env ]; then
            source .validate.env
          fi
          check_all.sh
